Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using SA51_CA_Project_Team10.DBs;
using SA51_CA_Project_Team10.Models;

namespace SA51_CA_Project_Team10.Controllers
{
    public class CartController : Controller
    {
        private readonly DbT10Software _db;
        private readonly Verify _v;

        public CartController (DbT10Software _db, Verify v)
        {
            this._db = _db;
            _v = v;
        }
        public IActionResult Index()
        {
            string sessionId = HttpContext.Request.Cookies["sessionId"];
            List<Cart> carts = new List<Cart>();
            //validate session 
            if (_v.VerifySession(sessionId, _db))
            {
                ViewData["Logged"] = true;
                User user = _db.Sessions.FirstOrDefault(s => s.Id == sessionId).User;

                ViewData["Username"] = user.Username;

                //retrieve product number labeled beside icon
                carts = _db.Carts.Where(x => x.UserId == user.Id).ToList();
            }
            else
            {
                string cartCookie = HttpContext.Request.Cookies["guestCart"];
                //tentative cart; now user not log in;
                if (cartCookie != null)
                {
                    var guestCart = JsonSerializer.Deserialize<GuestCart>(HttpContext.Request.Cookies["guestCart"]);
                    carts = guestCart.LoadProducts(_db);
                }
            }

            if (carts.Count == 0)
            {
                // Returns alternate view if there are no items
                ViewData["CartQuantity"] = 0;
                ViewData["Total"] = 0;
                carts = null;
            } else
            {
                ViewData["CartQuantity"] = carts.Sum(cart => cart.Quantity);
                ViewData["ItemsInCart"] = carts;
                ViewData["Total"] = carts.Sum(cart => cart.Quantity * cart.Product.Price);
            }

            return View(carts);

        }

        public IActionResult Checkout(Hasher h)
        {
            string sessionId = HttpContext.Request.Cookies["sessionId"];

            if (_v.VerifySession(sessionId, _db))
            {
                User user = _db.Sessions.FirstOrDefault(session => session.Id == sessionId).User;
                List<Cart> carts = _db.Carts.Where(cart => cart.UserId == user.Id).ToList();

                var order = new Order
                {
                    UserId = user.Id,
                    DateTime = DateTime.Now
                };

                foreach (Cart c in carts)
                {
                    for (int i = 0; i < c.Quantity; i++)
                    {
                        var orderDetail = new OrderDetail
                        {
                            Id = h.GenerateActivationKey(_db),
                            Order = order,
                            ProductId = c.ProductId
                        };
                        _db.OrderDetails.Add(orderDetail);
                    }
                    _db.Carts.Remove(c);
                }

                _db.SaveChanges();
                TempData["Alert"] = "primary|Successful checkout!";

            } else
            {
                TempData["ReturnUrl"] = "/Cart/Index";
                TempData["Alert"] = "danger|Login is required to checkout, please login.";
                return Redirect("/Login/Index");
            }
            return Redirect("/Purchase");
        }

        [HttpPost]
        public JsonResult Update(int productId, int quantity)
        {
            string sessionId = HttpContext.Request.Cookies["sessionId"];
            string newPrice;
            string totalPrice;

            if (_v.VerifySession(sessionId, _db))
            {
                User user = _db.Sessions.FirstOrDefault(session => session.Id == sessionId).User;
                Cart cart = _db.Carts.FirstOrDefault(cart => cart.UserId == user.Id && cart.ProductId == productId);

                cart.Quantity = quantity;

                _db.SaveChanges();

                newPrice = (cart.Quantity * cart.Product.Price).ToString();
                totalPrice = (_db.Carts.Where(cart => cart.UserId == user.Id).Sum(cart => cart.Quantity * cart.Product.Price)).ToString();

            } else
            {
                var guestCart = JsonSerializer.Deserialize<GuestCart>(HttpContext.Request.Cookies["guestCart"]);
                double priceSum = 0;

                foreach (var product in guestCart.Products)
                {
                    if (product.ProductId == productId)
                    {
                        product.Quantity = quantity;
                    }
                    priceSum += _db.Products.FirstOrDefault(p => p.Id == product.ProductId).Price * product.Quantity;
                }
                HttpContext.Response.Cookies.Append("guestCart", JsonSerializer.Serialize<GuestCart>(guestCart));

                newPrice = (_db.Products.FirstOrDefault(product => product.Id == productId).Price * quantity).ToString();
                totalPrice = priceSum.ToString();
            }

            return Json(new
            {
                success = true,
                newPrice,
                totalPrice
            });
        }

        [HttpPost]
        public JsonResult Remove(int productId, int row)
        {
            string sessionId = HttpContext.Request.Cookies["sessionId"];
            string totalPrice;

            if (_v.VerifySession(sessionId, _db))
            {
                User user = _db.Sessions.FirstOrDefault(session => session.Id == sessionId).User;
                Cart cart = _db.Carts.FirstOrDefault(cart => cart.UserId == user.Id && cart.ProductId == productId);

                _db.Carts.Remove(cart);

                _db.SaveChanges();
                totalPrice = (_db.Carts.Where(cart => cart.UserId == user.Id).Sum(cart => cart.Quantity * cart.Product.Price)).ToString();
            }
            else
            {
                var guestCart = JsonSerializer.Deserialize<GuestCart>(HttpContext.Request.Cookies["guestCart"]);
                double priceSum = 0;
                Cart productToRemove = null;

                foreach (var product in guestCart.Products)
                {
                    if (product.ProductId == productId)
                    {
                        productToRemove = product;
                        continue;
                    }
                    priceSum += _db.Products.FirstOrDefault(p => p.Id == product.ProductId).Price * product.Quantity;
                }

                if (productToRemove != null)
                {
                    guestCart.Products.Remove(productToRemove);
                }

                HttpContext.Response.Cookies.Append("guestCart", JsonSerializer.Serialize<GuestCart>(guestCart));
                totalPrice = priceSum.ToString();
            }

            return Json(new
            {
                success = true,
                totalPrice,
            });
        }

    }
}

Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Castle.Core.Internal;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Logging;
using SA51_CA_Project_Team10.DBs;
using SA51_CA_Project_Team10.Models;

namespace SA51_CA_Project_Team10.Controllers
{
    public class GalleryController : Controller
    {
        private readonly DbT10Software _db;
        private readonly Verify _v;
        private readonly ILogger<GalleryViewModel> _logger;
        public GalleryController(DbT10Software db, Verify v, ILogger<GalleryViewModel> logger) {
            _db = db;
            _v = v;
            _logger = logger;
        }
        public IActionResult Index(string search, int page = 1)
        {
            string sessionId = HttpContext.Request.Cookies["sessionId"];
            User user = null;
            //validate session
            if (_v.VerifySession(sessionId, _db))
            {
                ViewData["Logged"] = true;
                try
                {
                    user = _db.Sessions.FirstOrDefault(x => x.Id == sessionId).User;
                    throw new Exception();
                }
                catch(Exception ex)
                {
                    _logger.LogError(ex.Message);
                    _logger.LogDebug(ex.Message);
                    _logger.Log(LogLevel.Critical, ex.Message);
                }
                ViewData["Username"] = user.Username;

                //retrieve product number labeled beside icon
                List<Cart> carts = _db.Carts.Where(x => x.UserId == user.Id).ToList();
                ViewData["CartQuantity"] = carts.Sum(cart => cart.Quantity);
            }      
            else{  
                //tentative cart
                string cartCookie = HttpContext.Request.Cookies["guestCart"];
                if (cartCookie == null)
                {
                    ViewData["CartQuantity"] = 0;
                }
                else {
                    var guestCart = JsonSerializer.Deserialize<GuestCart>(HttpContext.Request.Cookies["guestCart"]);
                    ViewData["CartQuantity"] = guestCart.Count();
                }
            }

            List<Product> products = new List<Product>();

            //searchbar logic & retrieve products list and pass to view
            if (search.IsNullOrEmpty())
            {
                products = _db.Products.OrderBy(x => x.Name).ToList();
            } else
            {
                products = _db.Products.Where(x => x.Name.Contains(search)).OrderBy(x => x.Name).ToList();
            }

            var galleryView = new GalleryViewModel(user, page, products);

            ViewData["Searchbar"] = search;

            return View(galleryView);
        }

        [HttpPost]
        public IActionResult AddCart(int productId) {
            string sessionId = HttpContext.Request.Cookies["sessionId"];

            if (_v.VerifySession(sessionId, _db))
            {
                int userid = _db.Sessions.FirstOrDefault(x => x.Id == sessionId).UserId;
                Cart cart = _db.Carts.FirstOrDefault(x => x.UserId == userid && x.ProductId == productId);

                // Special case handling to prevent integer overflow
                if (cart == null)
                {
                    _db.Add(new Cart()
                    {
                        Quantity = 1,
                        UserId = userid,
                        ProductId = productId
                    });
                }
                else if (cart.Quantity < 100)
                {
                    cart.Quantity += 1;
                } else
                {
                    TempData["Alert"] = "warning|Cannot have more than 100 of the same product at once in cart, please contact Team 10 for bulk purchases.";
                    return Json(new
                    {
                        success = false,
                    });
                }

                _db.SaveChanges();

                return Json(new
                {
                    success = true
                });
            } else 
            {
                string cartCookie = HttpContext.Request.Cookies["guestCart"];
                GuestCart guestCart;
                if (cartCookie != null)
                {
                    guestCart = JsonSerializer.Deserialize<GuestCart>(cartCookie);
                }
                else
                {
                    guestCart = new GuestCart();
                    guestCart.Add(productId, _db.Products.FirstOrDefault(p => p.Id == productId));
                }

                Product product = _db.Products.FirstOrDefault(p => p.Id == productId);
                Cart inCart = guestCart.Find(productId);

                // Special case handling to prevent integer overflow
                if (inCart == null || inCart.Quantity < 100)
                {
                    guestCart.Add(productId, product);
                } else
                {
                    TempData["Alert"] = "warning|Cannot have more than 100 of the same product at once in cart, please contact Team 10 for bulk purchases.";
                    return Json(new
                    {
                        success = false,
                    });
                }

                HttpContext.Response.Cookies.Append("guestCart", JsonSerializer.Serialize<GuestCart>(guestCart), new CookieOptions
                {
                    HttpOnly = true,
                    SameSite = SameSiteMode.Lax
                });
                
                return Json(new
                {
                    success = true
                });
            }
        }

        [HttpPost]
        public IActionResult Rate(int rating, int productId)
        {
            string sessionId = HttpContext.Request.Cookies["sessionId"];

            if (_v.VerifySession(sessionId, _db))
            {
                User user = _db.Sessions.FirstOrDefault(session => session.Id == sessionId).User;

                _db.Ratings.Add(new Rating
                {
                    UserId = user.Id,
                    ProductId = productId,
                    Score = rating
                });

                _db.SaveChanges();

                return Json(new
                {
                    success = true,
                    newAverage = Math.Round(_db.Ratings.Where(rating => rating.ProductId == productId).Average(rating => rating.Score) * 2) / 2
                });
            }
            else
            {
                TempData["Alert"] = "primary|Please log in to rate products.";
                return Json(new
                {
                    success = false,
                    redirect = "/Login/Index"
                });
            }
        }
    }
}

Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SA51_CA_Project_Team10.DBs;
using SA51_CA_Project_Team10.Models;

namespace SA51_CA_Project_Team10.Controllers
{
    public class LogoutController : Controller
    {
        private readonly DbT10Software _db;
        public LogoutController(DbT10Software db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            string sessionId = HttpContext.Request.Cookies["sessionId"];

            _db.Sessions.Remove(new Session()
            {
                Id = sessionId
            });
            _db.SaveChanges();

            HttpContext.Response.Cookies.Delete("sessionId");

            TempData["Alert"] = "primary|Successfully logged out!";
            return Redirect("/Gallery/Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

@{
    if ((string)ViewData["Title"] == "فروشگاه اینترنتی کفش" && ViewData["Username"] != null)
    {
        ViewData["Main"] = $"سلام {ViewData["Username"]}";
    } else
    {
        ViewData["Main"] = ViewData["Title"];
    }

    string[] alert = new string[2];
    if (TempData["Alert"] != null)
    {
        alert = ((string)TempData["Alert"]).Split("|");
    }

}

<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/table.css" />
    <link rel="stylesheet" href="~/css/added.css" />
     @await RenderSectionAsync("Head", required: false)
</head>
<body style="font-family:Yekan">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <span class="navbar-brand" >@ViewData["Main"]</span>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse mr-auto">
                    <ul class="navbar-nav flex-grow-1">
                        @if ((string)ViewData["Title"] == "مشاهده کارت")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Gallery" asp-action="Index">ادامه دادن به خرید</a>
                            </li>
                            <li class="nav-item">
                                <span class="nav-link text-dark" style="color:black !important;">|</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Cart" asp-action="Checkout">پرداخت</a>
                            </li>
                        }
                        else if ((string)ViewData["Title"] == "Login")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Gallery" asp-action="Index">لیست محصولات</a>
                            </li>
                        }

                        @if ((string)ViewData["Title"] == "فروشگاه اینترنتی کفش" || (string)ViewData["Title"] == "خریدهای من")
                        {
                            if ((string)ViewData["Title"] == "فروشگاه اینترنتی کفش")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Purchase" asp-action="Index">لیست خرید من</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Gallery" asp-action="Index">صفحه اصلی</a>
                                </li>
                            }
                            <li class="nav-item">
                                <span class="nav-link text-dark" style="color:black !important;">|</span>
                            </li>
                            @if (ViewData["Logged"] != null && (bool)ViewData["Logged"])
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark " asp-controller="Logout" asp-action="Index">خروج از فروشگاه</a>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-controller="Login" asp-action="Index">ورود به سیستم</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
                <div class="ml-auto">
                    <ul class="navbar-nav flex-grow-1">
                        @if ((string)ViewData["Title"] == "فروشگاه اینترنتی کفش")
                        {
                            <li class="nav-item">
                                <a asp-controller="Cart" asp-action="Index"><img src="~/images/cart_icon.png" height="40" width="40" /></a>
                            </li>
                            <li class="nav-item">
                                <a class="text-dark" id="cartnum" asp-controller="Cart" asp-action="Index">@ViewData["CartQuantity"]</a>
                            </li>
                        }
                        else if ((string)ViewData["Title"] == "مشاهده کارت")
                        {
                            <li class="nav-item">
                                <a id ="totalPrice" class="nav-link text-dark" style="color:black !important;">جمع خرید: تومان @ViewData["Total"]</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["Alert"] != null)
            {
                <div class="alert alert-@alert[0] fade show" role="alert">
                    @alert[1]
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>